In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv(r"C:\Users\Admin\Downloads\train.csv")

In [5]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
df=df.drop("Cabin",axis =1)
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare Embarked  
0        1      0         A/5 21171   7.2500        S  
1        1      0          PC 17599  71.2833        C  
2        0      0  STON/O2. 3101282   7.9250        S  
3        1      0            113803  53.1000        S  
4        0      0            373450   8.0500        S  
..     ...    ...               ...      ...      ...  
886      0      0            211536  13.0000        S  
887      0      0            112053  30.0000        S  
888      1      2        W./C. 6607  23.4500        S  
889      0      0            111369  30.0000        C  
890      0      0            370376   7.7500        Q  

[891 rows x 11 columns]

In [10]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [11]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [12]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [13]:
df.duplicated().sum()

0

In [14]:
df["Embarked"].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [15]:
df.replace("S",1,inplace =True)#To replace the values and inplace to make it permanent
df.replace("C",2,inplace =True)
df.replace("Q",3,inplace =True)
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare  Embarked  
0        1      0         A/5 21171   7.2500         1  
1        1      0          PC 17599  71.2833         2  
2        0      0  STON/O2. 3101282   7.9250         1  
3        1      0            113803  53.1000         1  
4        0      0            373450   8.0500         1  
..     ...    ...               ...      ...       ...  
886      0      0            211536  13.0000         1  
887      0      0            112053  30.0000         1  
888      1      2        W./C. 6607  23.4500         1  
889      0      0            111369  30.0000         2  
890      0      0            370376   7.7500         3  

[891 rows x 11 columns]

In [16]:
df["Embarked"].head()

0    1
1    2
2    1
3    1
4    1
Name: Embarked, dtype: int64

In [17]:
df = df.drop("Name", axis=1)
df
df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare  Embarked  
0         A/5 21171   7.2500         1  
1          PC 17599  71.2833         2  
2  STON/O2. 3101282   7.9250         1  
3            113803  53.1000         1  
4            373450   8.0500         1

In [18]:
df["Age"]=df["Age"].astype("int")
df["Fare"]=df["Fare"].astype("int")
df.replace("male",0,inplace =True)#To replace the values and inplace to make it permanent
df.replace("female",5,inplace =True)
df

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch            Ticket  \
0              1         0       3    0   22      1      0         A/5 21171   
1              2         1       1    5   38      1      0          PC 17599   
2              3         1       3    5   26      0      0  STON/O2. 3101282   
3              4         1       1    5   35      1      0            113803   
4              5         0       3    0   35      0      0            373450   
..           ...       ...     ...  ...  ...    ...    ...               ...   
886          887         0       2    0   27      0      0            211536   
887          888         1       1    5   19      0      0            112053   
888          889         0       3    5   29      1      2        W./C. 6607   
889          890         1       1    0   26      0      0            111369   
890          891         0       3    0   32      0      0            370376   

     Fare  Embarked  
0       7         1  
1      71         2  
2       7         1  
3      53         1  
4       8         1  
..    ...       ...  
886    13         1  
887    30         1  
888    23         1  
889    30         2  
890     7         3  

[891 rows x 10 columns]

In [19]:
df["Ticket"].value_counts()

347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: Ticket, Length: 681, dtype: int64

In [20]:
def replace_non_numeric_with_1000(value):
    try:
        # Try to convert the value to a numeric (int or float)
        return int(value)
    except :
        # If the conversion fails, return 1000
        return 1000
df["Ticket"] = df["Ticket"].apply(replace_non_numeric_with_1000)

print(type(df["Ticket"]))
df.info()
df["Ticket"].value_counts()

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    int64
 4   Age          891 non-null    int32
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    int64
 8   Fare         891 non-null    int32
 9   Embarked     891 non-null    int64
dtypes: int32(2), int64(8)
memory usage: 62.8 KB


1000       230
1601         7
347082       7
347088       6
3101295      6
          ... 
248740       1
113784       1
7598         1
349225       1
370376       1
Name: Ticket, Length: 515, dtype: int64

In [21]:
x = df.drop("Embarked", axis=1)#specifically col

In [22]:
x

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Ticket  Fare
0              1         0       3    0   22      1      0    1000     7
1              2         1       1    5   38      1      0    1000    71
2              3         1       3    5   26      0      0    1000     7
3              4         1       1    5   35      1      0  113803    53
4              5         0       3    0   35      0      0  373450     8
..           ...       ...     ...  ...  ...    ...    ...     ...   ...
886          887         0       2    0   27      0      0  211536    13
887          888         1       1    5   19      0      0  112053    30
888          889         0       3    5   29      1      2    1000    23
889          890         1       1    0   26      0      0  111369    30
890          891         0       3    0   32      0      0  370376     7

[891 rows x 9 columns]

In [23]:
y = df["Embarked"]

In [24]:
y

0      1
1      2
2      1
3      1
4      1
      ..
886    1
887    1
888    1
889    2
890    3
Name: Embarked, Length: 891, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.65,random_state=20)#x_train,test and y_train,test please change at karna

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
clf = DecisionTreeClassifier()
clf.fit(X_train, Y_train)

DecisionTreeClassifier()

In [28]:
y_pred = clf.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 3, 3, 1, 1, 3, 3, 1, 1, 1,
       1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 3, 3, 2,
       1, 2, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 3, 2, 1, 1, 2, 1, 1, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 3, 2, 3,
       2, 3, 1, 1, 3, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 3, 1, 2, 1, 1, 1,
       2, 2, 1, 3, 3, 2, 1, 2, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3,
       1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 2, 2, 1, 3, 2, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 2, 2, 1, 1, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 2, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3, 1, 1, 2, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 3, 1, 1, 1, 1,

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8717948717948718


In [34]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(X_train,Y_train)#LogisticRegression() function call kar raha hai

LogisticRegression()

In [35]:
y_pred=log.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [43]:
from sklearn.metrics import confusion_matrix,f1_score,precision_score,accuracy_score,recall_score

In [39]:
conf=confusion_matrix(Y_test,y_pred)
print(conf)

[[205  14   3]
 [ 23  37   0]
 [  5   0  25]]


In [41]:
f1=f1_score(Y_test,y_pred,average='weighted')
print(f1)

0.8522629006713888


In [45]:
re=recall_score(Y_test,y_pred,average='weighted')
print(re)

0.8557692307692307


In [47]:
acc=accuracy_score(Y_test,y_pred)
print(acc)

0.8557692307692307


In [37]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.neighbors import KNeighborsClassifier

# Create a KNN classifier with a specified value of K
knn = KNeighborsClassifier(n_neighbors=5)  # You can change the value of n_neighbors

# Training the classifier with your data
knn.fit(X_train, Y_train)  

# Making predictions on new data
y_pred = knn.predict(X_test)  


accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.8557692307692307
